from django.conf.urls import url, include

from django.views.generic import TemplateView
from . import views, user_views, experiment_views, sample_views, dosimeter_views, irradiation_views, compound_views



urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<experiment_id>[0-9]+)/experiment/$', experiment_views.experiment_details, name='experiment_details'),
    url(r'^logged_user/$',  user_views.view_user, name='view_user'),
    url(r'^experiments/$', experiment_views.experiments_list, name='experiments_list'),
    url(r'^user/(?P<pk>\d+)/experiments/$', experiment_views.admin_experiments_user_view, name='admin_experiments_user_view'),
    url(r'^admin/experiments/$', experiment_views.admin_experiments_list, name='admin_experiments_list'),
    url(r'^experiments/history/$', experiment_views.admin_experiments_list, name='experiments_history'),
    url(r'^experiment/new/$', experiment_views.experiment_new, name='experiment_new'),
    url(r'^experiments/(?P<pk>\d+)/update/$', experiment_views.experiment_update, name='experiment_update'),
    url(r'^experiments/(?P<pk>\d+)/delete/$', experiment_views.experiment_delete, name='experiment_delete'),
    url(r'^experiments/(?P<pk>\d+)/clone/$', experiment_views.experiment_clone, name='experiment_clone'),
    url(r'^experiments/(?P<pk>\d+)/validate/$', experiment_views.experiment_validate, name='experiment_validate'),
    url(r'^experiments/(?P<pk>\d+)/status/$', experiment_views.experiment_status_update, name='experiment_status_update'),
    url(r'^experiments/(?P<pk>\d+)/print/$', views.print_experiment_view, name='print_experiment_view'),
    url(r'^users/$',  user_views.users_list, name='users_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/users/$',  user_views.experiment_users_list, name='experiment_users_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/user/new/$',  user_views.user_new, name='user_new'),
    url(r'^user/new/$',  user_views.admin_user_new, name='admin_user_new'),
    url(r'^experiment/(?P<experiment_id>\d+)/user/(?P<pk>\d+)/update/$', user_views.user_update, name='user_update'),
    url(r'^experiment/(?P<experiment_id>\d+)/user/(?P<pk>\d+)/delete/$', user_views.user_delete_from_experiment, name='user_delete_from_experiment'),
    url(r'^user/(?P<pk>\d+)/delete/$', user_views.admin_user_delete, name='admin_user_delete'),
    url(r'^user/(?P<pk>\d+)/update/$', user_views.admin_user_update, name='admin_user_update'),
    url(r'^regulations/$',views.regulations, name='regulations'),
    url(r'^fluence_conversion/$',views.fluence_conversion, name='fluence_conversion'),
    url(r'^experiment/(?P<experiment_id>\d+)/samples/$', sample_views.experiment_samples_list, name='experiment_samples_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/new/$', sample_views.sample_new, name='sample_new'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/update/$', sample_views.sample_update, name='sample_update'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/clone/$', sample_views.sample_clone, name='sample_clone'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/delete/$', sample_views.sample_delete, name='sample_delete'),
    url(r'^experiment/(?P<experiment_id>\d+)/samples/move_samples/$', sample_views.move_samples, name='move_samples'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/print/label/$', views.print_sample_label_view, name='print_sample_label_view'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/print/$', views.print_sample_view, name='print_sample_view'),
    url(r'^dosimeters/$',  dosimeter_views.dosimeters_list, name='dosimeters_list'),
    url(r'^dosimeter/new/$',  dosimeter_views.dosimeter_new, name='dosimeter_new'),
    url(r'^dosimeter/(?P<pk>\d+)/update/$',  dosimeter_views.dosimeter_update, name='dosimeter_update'),
    url(r'^dosimeter/(?P<pk>\d+)/clone/$',  dosimeter_views.dosimeter_clone, name='dosimeter_clone'),
    url(r'^dosimeter/(?P<pk>\d+)/delete/$',  dosimeter_views.dosimeter_delete, name='dosimeter_delete'),
    url(r'^dosimeter/(?P<pk>\d+)/print/label/$', views.print_dosimeter_label_view, name='print_dosimeter_label_view'),
    url(r'^experiment/(?P<experiment_id>\d+)/dosimeter/assign/$', dosimeter_views.assign_dosimeters, name='assign_dosimeters'),
    url(r'^dosimeters/generate/ids/$', dosimeter_views.generate_dos_ids, name='generate_dos_ids'),
    url(r'^irradiations/$', irradiation_views.irradiations, name='irradiations'),
    url(r'^search_irradiations/$', views.search_irradiations, name='search_irradiations'),
    url(r'^search/experiment/(?P<experiment_id>\d+)/sample$', sample_views.search_samples, name='search_samples'),
    url(r'^search/sample$', sample_views.search_single_sample, name='search_single_sample'),
    url(r'^search/experiments/user$', views.search_experiments_user, name='search_experiments_user'),
    url(r'^search/admin/experiments/$', views.search_experiments_admin, name='search_experiments_admin'),
    url(r'^search/experiment/(?P<experiment_id>\d+)/users/$', views.search_experiment_users, name='search_experiment_users'),
    url(r'^search/admin/users/$', views.search_users_admin, name='search_users_admin'),
    url(r'^search/dosimeters/$', views.search_dosimeters, name='search_dosimeters'),
    url(r'^admin/compound/new/$', compound_views.admin_compound_new, name='admin_compound_new'),
    url(r'^admin/compound/(?P<pk>\d+)/update/$', compound_views.admin_compound_update, name='admin_compound_update'),
    url(r'^admin/compound/(?P<pk>\d+)/delete/$', compound_views.admin_compound_delete, name='admin_compound_delete'),
    url(r'^experiment/(?P<experiment_id>\d+)/compound/new/$', compound_views.compound_new, name='compound_new'),
    url(r'^compounds/$', compound_views.compounds_list, name='compounds_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/assign_set_ids/$', sample_views.assign_set_ids, name='assign_set_ids'),
    url(r'^experiment/(?P<experiment_id>\d+)/archive/samples/$', sample_views.archive_experiment_samples, name='archive_experiment_samples'),
    url(r'^experiment/(?P<experiment_id>\d+)/new/irradiation/$', irradiation_views.new_group_irradiation, name='new_group_irradiation'),
    url(r'^irradiation/new/$', irradiation_views.irradiation_new, name='irradiation_new'),
    url(r'^irradiation/(?P<pk>\d+)/update/$', irradiation_views.irradiation_update, name='irradiation_update'),
    url(r'^irradiation/(?P<pk>\d+)/delete/$', irradiation_views.irradiation_delete, name='irradiation_delete'),
    url(r'^irradiation/(?P<pk>\d+)/status/update/$', irradiation_views.irradiation_status_update, name='irradiation_status_update'),
    url(r'^register/preferences/$', views.register_preferences, name='register_preferences'),
    url(r'^change/experiment/(?P<pk>\d+)/visibility/$', experiment_views.change_experiment_visibility, name='change_experiment_visibility'),
    url(r'^change/experiment/(?P<pk>\d+)/visibility/on/$', experiment_views.change_experiment_visibility, name='change_experiment_visibility_on'),
    url(r'^change/experiment/(?P<pk>\d+)/visibility/off/$', experiment_views.change_experiment_visibility, name='change_experiment_visibility_off'),
    url(r'^get/sec/$', views.get_sec, name='get_sec'),
    url(r'^admin/dosimetry/results/$', irradiation_views.admin_dosimetry_results, name='admin_dosimetry_results'),
    url(r'^sample/(?P<sample_id>\d+)/dosimetry/results/$', irradiation_views.dosimetry_results, name='dosimetry_results'),
    url(r'^irradiation/beam/change/$', views.in_beam_change, name='in_beam_change'),
    url(r'^select_table/$', views.select_table, name='select_table'),
    url(r'^experiment/(?P<pk>\d+)/comment/$', experiment_views.experiment_comment_update, name='experiment_comment_update'),
    url(r'^read/(?P<pk>\d+)/trec$', views.read_sample_trec, name='read_sample_trec'),
    url(r'^samples/$',sample_views.admin_samples_list, name='admin_samples_list'),
    ]
